Print errors to stderr

diff --git a/bin/atools-common b/bin/atools-common
--- a/bin/atools-common
+++ b/bin/atools-common
@@ -10,17 +10,17 @@ export ATOOLS_CACHE_PATH=$HOME/.cache/atools
 mkdir -p $ATOOLS_CACHE_PATH
 
 function info (){
-  echo -e "\033[0;32m-> \033[0m\033[0;01m $1\033[0;0m"
+  >&2 echo -e "\033[0;32m-> \033[0m\033[0;01m $1\033[0;0m"
 }
 
 function error (){
-  echo -e "\033[0;31m[ERROR] \033[0m\033[0;01m $1\033[0;0m"
-  echo "Exiting."
+  >&2 echo -e "\033[0;31m[ERROR] \033[0m\033[0;01m $1\033[0;0m"
+  >&2 echo "Exiting."
   exit -1
 }
 
 function warn (){
-  echo -e "\033[0;33m[WARN] \033[0m\033[0;01m $1\033[0;0m"
+  >&2 echo -e "\033[0;33m[WARN] \033[0m\033[0;01m $1\033[0;0m"
 }
 
 
