Add `current_script` function and replace $ATOOLS_PROGNAME uses with it

diff --git a/bin/atools-common b/bin/atools-common
--- a/bin/atools-common
+++ b/bin/atools-common
@@ -9,12 +9,18 @@ export ATOOLS_CACHE_PATH=$HOME/.cache/atools
 
 mkdir -p $ATOOLS_CACHE_PATH
 
+function current_script() {
+  a=()
+  a=($(tr '-' ' ' <<< $1))
+  echo "atools ${a[1]}"
+}
+
 function info (){
   >&2 echo -e "\033[0;32m-> \033[0m\033[0;01m $1\033[0;0m"
 }
 
 function error (){
-  >&2 echo -e "\033[0;31m[ERROR] \033[0m\033[0;01m $1\033[0;0m"
+  >&2 echo -e "\033[0;31m[ERROR]\033[0m\033[0;01m $1\033[0;0m"
   >&2 echo "Exiting."
   exit -1
 }
@@ -35,3 +41,4 @@ function get_api_info() {
   fi
   cat $cache_path
 }
+
